// <auto-generated>
// Rewired Constants
// This list was generated on 12/23/2019 5:40:13 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Look Horizontal")]
        public const int LookHorizontal = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Look Vertical")]
        public const int LookVertical = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Open Menu")]
        public const int OpenMenu = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Next")]
        public const int Next = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Previous")]
        public const int Previous = 10;
        // FPS
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "First Person Shooter", friendlyName = "Move Z")]
        public const int MoveZ = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "First Person Shooter", friendlyName = "Move X")]
        public const int MoveX = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "First Person Shooter", friendlyName = "Jump")]
        public const int Jump = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "First Person Shooter", friendlyName = "Sprint")]
        public const int Sprint = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "First Person Shooter", friendlyName = "Crawl")]
        public const int Crawl = 16;
        // Creative
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Creative Mode", friendlyName = "Fly Z")]
        public const int FlyZ = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Creative Mode", friendlyName = "Fly X")]
        public const int FlyX = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Creative Mode", friendlyName = "Fly Y")]
        public const int FlyY = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Creative Mode", friendlyName = "Place")]
        public const int Place = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Creative Mode", friendlyName = "Destroy")]
        public const int Destroy = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Creative Mode", friendlyName = "Fly Faster")]
        public const int FlyFaster = 8;
    }
    public static partial class Category {
        public const int Default = 0;
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
        }
        public static partial class Keyboard {
            public const int Default = 0;
        }
        public static partial class Mouse {
            public const int Default = 0;
        }
        public static partial class CustomController {
            public const int Default = 0;
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Player 1")]
        public const int Player1 = 0;
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
